---

- name: Create Kubernetes Cluster
  hosts: localhost
  gather_facts: no
  roles:
    - role: federated-cluster
      GOOGLE_CLOUD_ACCOUNT: huntermacdonald7@gmail.com
      GOOGLE_CLOUD_PROJECT: sedex-dev
      DNS_NAME: test-federation.com.
      MACHINE_TYPE: g1-small
      CLUSTER_PREFIX: dev
      CLUSTER_NODE_COUNT: 1
      MIN_NODE_COUNT: 1
      MAX_NODE_COUNT: 1
      ZONES:
        - europe-west1-b
        - asia-east1-b
