---

# TODO: need to check if secret was already created, if not skip (remove ignore_errors: yes)
# - name: add cluster kubeconfig for {{ item }}
#   command: >
#     kubectl --namespace=federation create secret generic {{ item }}
#     --from-file=generated/kubeconfigs/{{ item }}/kubeconfig

- name: run creater cluster manifest for {{ item }}
  command: kubectl --context=federation-cluster apply -f generated/manifests/{{ item }}-cluster.yaml
