apiVersion: federation/v1beta1
kind: Cluster
metadata:
  name: {{ item.0 }}
spec:
  serverAddressByClientCIDRs:
    - clientCIDR: "0.0.0.0/0"
      serverAddress: "{{ item.2 }}"
  secretRef:
    name: {{ item.0 }}
